name: "CI-CD Pipeline: Build, Test and publish artifact"

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

env:
  JDK_VERSION: 21

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: temurin
          cache: maven

      - name: Grant Maven wrapper permission
        run: chmod +x ./mvnw

      - name: Run Build and Tests
        run: ./mvnw clean verify

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: junit-reports
          path: '**/target/surefire-reports/'

  publish:
    name: Publish JAR Release Artifact
    runs-on: ubuntu-latest\
    if: github.event == 'push' && github.ref == 'refs/heads/master' || github.event == 'push' && github.ref == 'refs/heads/develop'
    needs: build_and_test

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: temurin
          cache: maven

      - name: Grant Maven wrapper permission
        run: chmod +x ./mvnw

      - name: Build JAR
        run: ./mvnw clean package -DskipTests

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v7
        with:
          name: carwash-booking-queue-system-jar
          path: target/*.jar


  Containerize:
    name: Containerize
    runs-on: ubuntu-latest
    if: github.event == 'push' && github.ref == 'refs/heads/master' || github.event == 'push' && github.ref == 'refs/heads/develop'
    needs: build_and_test

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Image Tag
        run: |
          BRANCH=${GITHUB_REF_NAME}
          SHA=$(git rev-parse --short HEAD)
          DATE=$(date +'%Y%m%d-%H%M%S')
          
          TAG="${BRANCH}-${SHA}-${DATE}"
          
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
          
          echo "Generated tag: $TAG"
          
      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/carwash-booking-queue-system:${IMAGE_TAG} \
            .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/carwash-booking-queue-system:${IMAGE_TAG}
